//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sharing.Agent.Synchronizer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sharing.Agent.Synchronizer.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xml&gt;
        ///&lt;return_code&gt;&lt;![CDATA[SUCCESS]]&gt;&lt;/return_code&gt;
        ///&lt;return_msg&gt;&lt;![CDATA[发放成功]]&gt;&lt;/return_msg&gt;
        ///&lt;result_code&gt;&lt;![CDATA[SUCCESS]]&gt;&lt;/result_code&gt;
        ///&lt;err_code&gt;&lt;![CDATA[SUCCESS]]&gt;&lt;/err_code&gt;
        ///&lt;err_code_des&gt;&lt;![CDATA[发放成功]]&gt;&lt;/err_code_des&gt;
        ///&lt;mch_billno&gt;&lt;![CDATA[T202002240000000025]]&gt;&lt;/mch_billno&gt;
        ///&lt;mch_id&gt;&lt;![CDATA[1520961881]]&gt;&lt;/mch_id&gt;
        ///&lt;wxappid&gt;&lt;![CDATA[wx20da9548445a2ca7]]&gt;&lt;/wxappid&gt;
        ///&lt;re_openid&gt;&lt;![CDATA[o18KQ54oC3bWFss8Zzk__G8CW9TU]]&gt;&lt;/re_openid&gt;
        ///&lt;total_amount&gt;100&lt;/total_amount&gt;
        ///&lt;send_listid&gt;&lt;![CDATA[100004 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RewardFailed {
            get {
                return ResourceManager.GetString("RewardFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xml&gt;
        ///&lt;return_code&gt;&lt;![CDATA[SUCCESS]]&gt;&lt;/return_code&gt;
        ///&lt;return_msg&gt;&lt;![CDATA[证书已过期]]&gt;&lt;/return_msg&gt;
        ///&lt;result_code&gt;&lt;![CDATA[FAIL]]&gt;&lt;/result_code&gt;
        ///&lt;err_code&gt;&lt;![CDATA[CA_ERROR]]&gt;&lt;/err_code&gt;
        ///&lt;err_code_des&gt;&lt;![CDATA[证书已过期]]&gt;&lt;/err_code_des&gt;
        ///&lt;mch_billno&gt;&lt;![CDATA[T202002240000000025]]&gt;&lt;/mch_billno&gt;
        ///&lt;mch_id&gt;&lt;![CDATA[1520961881]]&gt;&lt;/mch_id&gt;
        ///&lt;wxappid&gt;&lt;![CDATA[wx20da9548445a2ca7]]&gt;&lt;/wxappid&gt;
        ///&lt;re_openid&gt;&lt;![CDATA[o18KQ54oC3bWFss8Zzk__G8CW9TU]]&gt;&lt;/re_openid&gt;
        ///&lt;total_amount&gt;80&lt;/total_amount&gt;
        ///&lt;/xml&gt;.
        /// </summary>
        public static string RewardSuccessfully {
            get {
                return ResourceManager.GetString("RewardSuccessfully", resourceCulture);
            }
        }
    }
}
